version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888
      - 6001:5005

  registry:
    build: registry
    ports:
      - 6002:5005

  gateway:
    build: gateway
    ports:
      - 6003:5005

  auth-service:
    build: auth-service
    ports:
      - 5000:5000
      - 6004:5005

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-service:
    build: account-service
    ports:
      - 6000:6000
      - 6005:5005

  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000
      - 6006:5005

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  notification-service:
    build: notification-service
    ports:
      - 8000:8000
      - 6007:5005

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017

  monitoring:
    build: monitoring
    ports:
      - 6008:5005

  turbine-stream-service:
    build: turbine-stream-service
    ports:
      - 6009:5005